services:
  - docker

install:
  - docker build -t ddiez/centipede-ms .

script:
  - docker run ddiez/centipede-ms centipede-ms -h

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push ddiez/centipede-ms;
    fi
